### ISSUE TITLE
UI for Device Agent

### ISSUE THREAD

**Issue by MarianRaphael** [flowforge/flowforge-device-agent#76]
## Description

As a user, I want a simple UI that can create a device.yml configuration file for the FlowForge Device Agent. This will make it easier for users to quickly onboard their devices and improve the overall user experience.

## Background

Currently, the FlowForge Device Agent requires a device.yml file to start. Creating and configuring this file can be challenging, especially when no direct shell access is possible. This process can become even more difficult for users who may lack the technical knowledge or expertise required to create and configure a device.yml file. This Epic aims to address these challenges by creating a User Interface that simplifies the process of creating a device.yml configuration file.

## Goals

- Develop a UI that allows users to create a device.yml file with the necessary configuration details.
- The UI design should be consistent with the existing FlowForge platform aesthetics.

```[tasklist]
- [ ] https://github.com/flowforge/flowforge-device-agent/issues/82
- [ ] https://github.com/flowforge/flowforge-device-agent/issues/83
- [ ] https://github.com/flowforge/flowforge-device-agent/issues/84
- [ ] https://github.com/flowforge/flowforge/issues/2199
```

**Comment by MarianRaphael** [comment]
### Discussion with @Steve-Mcl 
Security to be considered -> (one possibility nr-tools-plugin appaorch), other preferred option **"Smart Home device" approach – 10 minutes to configure your device.yml** 

Key question:
Do we want to tackle the “Greenfield approach” (Device Agent preinstalled)? 
If yes -> No way around a UI 
If no -> A interactive CLI is sufficient

**Comment by Steve-Mcl** [comment]
## Following discussions with Marian and Nick

### Definitions and personas used in the discussion:

#### Greenfield situation
Consideration to pre-installed environments (like ctrlX or opto) devices where shell access is restricted or difficult (e.g. requires a developer key or "unsafe" options switched on). 

#### Brownfield situation
Situations where existing devices (be that off the shelf manufacturing devices, Rasp Pi, or re-purposed computers) are to be utilised for the FlowForge Device Agent.

#### The [PLC Engineer](https://flowforge.com/handbook/product/personas/#peter%2C-plc-engineer) was the main focus as someone who is trying to simplify adoption of new IIoT "things" (like Node-RED) and therefore prefers a UI or wizard over Command Line configuration


### Foreword
It was determined the "greenfield approach" is something we should explore as we already have a (somewhat non-optimised, but perfectly viable) existing solution for "brownfield" situations where the user can install the agent and apply a token via CLI or remote shell.


### MVP
In this first iteration, we have decided to take the following approach:
1. A minimal (but FF familiar) UI will be available when a flag is set that permits setup of the agent
2. The UI will permit the upload of a device.yml 
   1. This can be an actual device token or a provisioning token
3. For MVP, the security model will be the "smart things" approach:
    1. UI will be active for only 10 minutes and will require a restart to become accessible once more
    2. Once a configuration is applied, the UI will be disabled.
4. Documentation should include reference to internal security measures (like limiting the device connectivity and remote access, VPNs/VLANs)

**Comment by Steve-Mcl** [comment]
Update to MVP (following Dev Demo 30-05-2023)

* Add link to docs in the home.html page of the device webmin UI
* Add basic status info to the UI - to aid user configuring the device
* Placeholder for device config textarea
* Rename Submit button to Apply. This should both apply and reload the agent
* Remove “Reload Agent” button

These are captured as tasks in https://github.com/flowforge/flowforge-device-agent/issues/83
