### ISSUE TITLE
Device Editor cannot pickup FF theme

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge-device-agent#89]
### Current Behavior

When remote editing a device, the user sees the original NR theme, not the FF branded one

### Expected Behavior

Device should have FF branded theme when accessed via the "Remote Device Editing" proxy/tunnel

### Steps To Reproduce

* Set device to developer mode
* Enable Editor access
* Open the devices editor

### Environment

- FlowForge version: 1.7-git
```[tasklist]
### Tasks
- [ ] https://github.com/flowforge/flowforge-device-agent/pull/107
- [ ] https://github.com/flowforge/flowforge-device-agent/issues/108
```

**Comment by Steve-Mcl** [comment]
There are several approaches to this task:

1. Build Device Editor into the launcher (common app for launcher and device editor
2. `require` the launcher (so that we get access to the themes
3. Revert the theme package back toa standalone repo and modify this & launcher to require the theme
4. A local script that pulls the theme dist in 
    4b. this could also be a CI/CD task)
5. A manual Task to copy theme dist files into this repo (with suitable update to readme)


These are written from most difficult to easiest. 

Obvious the quick wins are 4 and 5. 

My personal preference would be No 4. We do something similar in the Node-RED monaco package where we download external packages and copy the required files into position.

**Comment by Steve-Mcl** [comment]
After discussion with @hardillb I have flipped this back to design stage.

The goal is to NOT host duplicate files.

One proposal is to keep the work already developed but run it as a NPM POST INSTALL on the users machine when they install the agent.  Just need to check that it works for our NPM workspace.  

A second alternative is a GIT submodule, and this will work however there may be a number of additional manual or CI/CD steps to maintain this arrangement.

**Comment by knolleary** [comment]
Having ready through the discussion in the associated PR, I think the only practical solution is to have the ff theme published to npm in its own package.

That doesn't mean moving the code back to its own repo; it could still live in the `nr-launcher` repo, but with an additional task that publishes it as a second module to npm whenever a release of `nr-launcher` is made.

`nr-launch` can continue to use the local copies of the files - anything else can require the theme module.

**Comment by Steve-Mcl** [comment]
Following discussion on slack and Nicks comment above, this is the proposed steps to complete this item:

REQUIRED:
- [ ] [Launcher] Publish theme to NPM https://github.com/flowforge/flowforge-nr-launcher/issues/134

OPTION 1:
- [ ] [Agent] Update Agent to add the theme as a dependency to device's package.json

OPTION 2:
- [ ] [Agent] Require the theme in the Agents package.json & utelising the work already completed in the PR, write out the theme files from the agents installation to the device directory. This (in theory) handles instances where the device has no access to NPM (since the relevant files would be copied from the agents installed files - kinda like we do for `writePackage`, `writeFlows` etc) - and also updates any existing device that does not have the theme installed.


@knolleary would appreciate your thoughts please.

**Comment by knolleary** [comment]
I don't believe option 2 is necessary. Option 1 will mean the theme is preinstalled within the device agent - so will be present wherever the agent is installed. If the device doesn't have npm access later on, it won't matter, the theme is already installed because the device agent is installed.

**Comment by knolleary** [comment]
Ah sorry - you *might* need some of option2 to make sure Node-RED picks up the theme; or we set the NODE_PATH appropriately to ensure it does get picked up without copying anything around.

**Comment by Steve-Mcl** [comment]
Thanks Nick, I will go with Option 1 as a base, test that theories & adjust to suit.

**Comment by knolleary** [comment]
We already have the theme on npm - https://www.npmjs.com/package/@flowforge/nr-theme - albeit a slightly older version, so we can make the device agent changes independently of the work to get that package refreshed from nr-launcher repo.

**Comment by Steve-Mcl** [comment]
Indeed. I will utelise that as a first port of call. (then later, concentrate on the NPM publish aspect). I will update tracking/task list to reflect this conversation.

**Comment by Steve-Mcl** [comment]
Verified on staging:



![Image](https://github.com/flowforge/flowforge-device-agent/assets/44235289/71847330-6263-456f-bf92-92eef0193a82)
